### ISSUE TITLE
Add byline to the blog

### ISSUE THREAD

**Issue by macruzbar** [knative/website#177]
## What is changing? (Please include as many details as possible.)
We are adding a static information field to blog entries on Knative.dev

## How will this impact our users?
Users will be able to know who is writing stories and can contact them if they need; Knative contributors can get more recognition for their work

## In what release will this take happen (to the best of your knowledge)?
N/A
ASAP

## Context
Link to associated PRs or issues from other repos here.

1. [Discussion at the last Knative documentation working group](https://docs.google.com/document/d/1Y7rug0XshcQPdKzptdWbQLQjcjgpFdLeEgP1nfkDAe4/edit#heading=h.cv7wz9yngwdt)
1.
1.

@evankanderson @carieshmarie @isdal

**Comment by evankanderson** [comment]
/kind good-first-issue

This probably involves updating this template: https://github.com/knative/website/blob/master/layouts/blog/baseof.html

**Comment by macruzbar** [comment]
@evankanderson how can we move this issue forward?

**Comment by bryeung** [comment]
/assign

(Sorry, still learning the github interface.)

**Comment by bryeung** [comment]
I'm not sure I understand the issue. If authors put an author line in the header of the blog entry, then it will already be rendered by the template.

See the attached fake blog entry and screenshot of how it renders.

<img width="410" alt="Screen Shot 2020-06-29 at 10 46 10 AM" src="https://user-images.githubusercontent.com/417798/86020373-d5019c00-b9f5-11ea-926c-75b10e4ec09a.png">
[author.html.txt](https://github.com/knative/website/files/4846224/author.html.txt)

**Comment by macruzbar** [comment]
It looks like we only need to request that blogpost submitters add the _author_ field on the template when they submit an .md file

```
---
title: "Author Example"
linkTitle: "Author Example"
author: "Jane Doe <jane@doe.org>"
date: 2020-06-29
description: "Demonstrating the author field."
type: "blog"
---
```

Closing this issue for now.

**Comment by macruzbar** [comment]
Hi @bryeung I tried [adding](https://github.com/knative/docs/pull/2623) the author field to the blog template, but [it didn't work](https://knative.dev/blog/2020/05/01/getting-started-with-knaitve-eventing-using-bitcoin-transaction-data/). I think we need to modify [the template](https://github.com/knative/website/blob/master/layouts/blog/baseof.html) for it to work, but I'm not sure where to add this

**Comment by bryeung** [comment]
When I tried to build the website with your change included, it failed. Do we not test this before merging?

Anyway, I think you just need to quote the author and it'll work:
https://github.com/knative/docs/pull/2629

There should be no change needed to the template.

**Comment by macruzbar** [comment]
> When I tried to build the website with your change included, it failed. Do we not test this before merging?
> 
> Anyway, I think you just need to quote the author and it'll work:
> [knative/docs#2629](https://github.com/knative/docs/pull/2629)
> 
> There should be no change needed to the template.

Thank you!
