### ISSUE TITLE
slack.knative.dev is 404

### ISSUE THREAD

**Issue by RichieEscarez** [knative/website#204]
The vanity URL slack.knative.dev no longer works (redirects to this non functioning "join Knative" link: https://join.slack.com/t/knative/shared_invite/enQtNDA1ODA1MTc2NjE1LTA3ODU5ZDlmMTg2N2MzMGI2NDc0YzkxMTg5MWRhNmZlYjgwMTM2NzE3ZThkYzgzMjE5ZTExYTMwMmEyZjk5ZTQ&usg=AOvVaw0A2SyTvfGCJV-cIeF5kLiK).
That vanity link is everywhere and currently displays a "This link is no longer active" page.
This issue was reported in the #docs channel regarding the site footer link but given that the vanity URL is everywhere (blogs, other product referral links, etc), is there another Slack join link that we can use to update the vanity URL redirect?

An alternative is to use: https://knative.slack.com/signup#/
But that page limits joining to only three domains:
![image](https://user-images.githubusercontent.com/11762685/91231587-56b63300-e6e2-11ea-9db7-12cf55c52291.png)

**Comment by evankanderson** [comment]
I think we previously had slack.knative.dev set up to redirect to a Slack invite link.

My recollection was that the invite link expired after 6 months, so the redirect needed to be updated around that time. I think Ryan Gregg did most of that work, so it's not surprising that some of that might have stopped working.

**Comment by evankanderson** [comment]
Here is an invite link that does work, but I don't have access to change slack.knative.dev :

https://join.slack.com/t/knative/shared_invite/zt-fzy43r2f-i4oJraPBHlBFp00v6NeI9w

**Comment by RichieEscarez** [comment]
Thanks @evankanderson, I'll try to push this through (maybe with help from @grantr)?

**Comment by RichieEscarez** [comment]
Looks like we need help from @chaodaiG (ive assigned the change)

**Comment by coryrc** [comment]
I'll see if I can make it redirect to the link Evan provided

**Comment by RichieEscarez** [comment]
@coryrc there should be a CL in your inbox

**Comment by coryrc** [comment]
In an incognito window, `slack.knative.dev` appears to be using Evan's new link

**Comment by RichieEscarez** [comment]
Thank you all for helping get the fix out!
