### ISSUE TITLE
Unable to create permanent link to docs for latest Knative release

### ISSUE THREAD

**Issue by bbrowning** [knative/website#25]
Today https://www.knative.dev/docs/ points to docs for the 0.4 releases of Knative. Soon that same URL will point to 0.5. What I'd like to be able to do is create a permanent link to the docs for any specific Knative version, even the most recent release.

I can create a permanent link for older docs, like the 0.3 release, as the URL looks like https://www.knative.dev/v0.3-docs/

But for the current release the URL does not have the version number and thus I can't create a permanent link to docs for that version. Nor does manually typing in https://www.knative.dev/v0.4-docs/ work until v0.4 is no longer the current release.

**Comment by RichieEscarez** [comment]
Ill investigate. My initial thought is that we stop using a generic /docs/ URL for the latest version and instead, always just redirect any /docs/ URL (ie. -> .../v0.5-docs/). The use of /docs/ stems from the Hugo templating site generator (/docs/ is a template definition) but ill look into our options for either redirecting, replacing /docs/, or implementing an intuitive user flow.

**Comment by bbrowning** [comment]
We could add a subfolder for the latest Knative release by adding a `cp -r` command around https://github.com/knative/website/blob/0eeeff1d4738ee96cd4afc2883a38a4c837dbe61/scripts/build.sh#L83-L88 to put the latest release docs under both `/docs/` and `/v-0.5-docs`. That would let someone manually create a permalink to docs for the latest release by editing the URL.

However, I do think a redirect from `/docs/` to the latest docs release `/v-0.5-docs/` would be reasonable default behavior.

**Comment by RichieEscarez** [comment]
For SEO and clarity, I'd like a solution that avoids duplicate content (ie single source of truth) -> having users hit /docs/ somethings and /v0.5/ sometimes wont provide clear search results.

Perhaps the inverse might also work? Where any knative.dev/**v0.?-docs**/ gets redirected to the /**docs**/ folder. Permanents links to that specific version would then persist and directly open to the right version as /v0.?-docs/ moves out of the default /docs/ folder into an actual /v0.?-docs/ folder.
